export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_FILTERED_CHARACTERS = 'GET_FILTERED_CHARACTERS';
export const GET_CHARACTER = 'GET_CHARACTER';
export const SET_MODAL_ACTIVE = 'SET_MODAL_ACTIVE';
export const ADD_CREATURES = 'ADD_CREATURES,';
export const ADD_CREATURES_SAGA = 'ADD_CREATURES_SAGA';
